hash-format = "sha256"

[[files]]
file = "config/NoChatReports/NCR-Client.json"
hash = "3d1d47349ad0c2e10180e70b19a3c112085a114275d7fe48e2e13d45c66bb1b8"

[[files]]
file = "config/NoChatReports/NCR-Common.json"
hash = "24b63114760a39586c80c8926039d7214171e652bce9eb2e233e2cd08b12072a"

[[files]]
file = "config/NoChatReports/NCR-Encryption.json"
hash = "df34a1ed7b309c08deaf42c906fa2ea6f29bb3bf8395ce26593fac4834938496"

[[files]]
file = "config/betterdeserttemples-fabric-1_19.toml"
hash = "d394143e5d0a30bf1fe441cdc942f042d04c3eef8b58fe2e506ef2a3ba0dc388"

[[files]]
file = "config/betterdungeons-fabric-1_19.toml"
hash = "9f699aa52db111f7ef46a98155261bc93ecf117fd6bffb154ce9f5cc1b4f9ec4"

[[files]]
file = "config/bettermineshafts-fabric-1_19.toml"
hash = "f61537c78da4a153c2f3bccc8fb5e36f846c9a4ed5b2535d7c18586c75c1d238"

[[files]]
file = "config/betteroceanmonuments-fabric-1_19.toml"
hash = "83480c3ded3411164452a248a520ed3171e3ca74634dd8361ed8f1360b991c0f"

[[files]]
file = "config/betterwitchhuts-fabric-1_19.toml"
hash = "c8cd377bdf72795ee5557b0394e224f8ccf8be82f641d2b75afad05e6856a7b7"

[[files]]
file = "config/extraalchemy.json"
hash = "9d08fd5d69678c60e9cd1ff672de8362bee8c380fe5feefdce0132163c180db3"

[[files]]
file = "config/hookshot.json5"
hash = "e9341c12c805bf998775525c083a9a059a0e3095a02a2f5d615c2ca164fd76cc"

[[files]]
file = "config/lightoverlay.properties"
hash = "677bbb11dbf6fe204d5341ea8c613e6b607f30833caf00bc90b9b3789cec3443"

[[files]]
file = "config/styledplayerlist/styles/default.json"
hash = "4573ad74b75f4cad01492a5bd14f826cb3e79dc2b865d7b0809aeb20acb4327d"

[[files]]
file = "mods/ad-astra.pw.toml"
hash = "6920f6c4434367cf5b2486b3fb321fe9c383dea5432cf627d091cab3bac944dc"
metafile = true

[[files]]
file = "mods/amplified-nether.pw.toml"
hash = "2e8a4921803a54bb9161d1120a5563efa746d3b11b180ff4a6a92e88837c574c"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "8fb3a2375531693a1fc0ac755bba4599e9c8331a399f51e1b1e1b9976109c22d"
metafile = true

[[files]]
file = "mods/arcanus-1.30.jar"
hash = "955325f1487e5118fb3c716d78b2771c4b8998302fded962636941351e71224f"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "651bb1998c83a40530d6cb95d40bd13e2f0f8ab064e0efdd3630f648cbe7f4ed"
metafile = true

[[files]]
file = "mods/bewitchment.pw.toml"
hash = "9d390f8378b38aa1ca9402721380827357552e12cff6c02cf272a9bfa8c39efa"
metafile = true

[[files]]
file = "mods/biome-makeover.pw.toml"
hash = "03d0cd0f8dc8c1c28e91ab07d62f9fdba448b3c5018eaf2e138796ecd101fa06"
metafile = true

[[files]]
file = "mods/biomesyougo.pw.toml"
hash = "dbbe09e6693b3c8608f7831b99f66ff57a62a5dfef612295cbe144553abd7336"
metafile = true

[[files]]
file = "mods/blast.pw.toml"
hash = "2a92db14f344c0a03eed49f7c5dccd49837bf1d81dc97c9b37793e5b75fbceb4"
metafile = true

[[files]]
file = "mods/bookshelf.pw.toml"
hash = "37031b97299b444d87cebb4c40091fca6130cc1ffd5d5eac7bd56ff1406cfa10"
metafile = true

[[files]]
file = "mods/botany-pots.pw.toml"
hash = "d392e1c9178699fb36dfc237a05c0569b4afae40f69b49701b61fad817fc7558"
metafile = true

[[files]]
file = "mods/botany-trees.pw.toml"
hash = "6a61ed2fb5f7cfe65d2f531119706c1020746e91511de5a6c917ecb83efe48ae"
metafile = true

[[files]]
file = "mods/catwalks-inc.pw.toml"
hash = "c0d1ff66a10e5853ae48c6021bbe4709461f451e71494f2f806004ece7b2965b"
metafile = true

[[files]]
file = "mods/cc-restitched.pw.toml"
hash = "6e8faa4779dca8bafd4cc91cad8f7fe425f6d3d08511463466c6c13b8ffa55dd"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "8440097630bb5576edaf891db7490fe9e6a6c996670e6d25b6bd027712db6050"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "c3c73a4ae07f1ab6de623b37007df3581286fe3495377af6d3da4b105892adb2"
metafile = true

[[files]]
file = "mods/consistencyplus.pw.toml"
hash = "0a82c23063612bf1baf43934323d8fca8dd23ddc2dc0a3db968f72d14b99e887"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "3cbe3d523b39667928fcc34f71651b0e581e5c541dd5ecf17228464770466bc5"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "19783c9eb3f9c3a9522f47f11fa9b87dd62b64a42e52cadbdf9ce9d5c8d73d46"
metafile = true

[[files]]
file = "mods/creeper-overhaul.pw.toml"
hash = "1809c5d6c6de929511d2cf7cda78ea9932dd9676a1cbab8292947f3b39cfd6f2"
metafile = true

[[files]]
file = "mods/cull-leaves.pw.toml"
hash = "65446ae773fb8f4f84b02d909f3b1dd45ceb09f956ac67ab3d96d362451c8a91"
metafile = true

[[files]]
file = "mods/dark-paintings.pw.toml"
hash = "51dca634f897c7840ec91bd734ddf837d18edfe80e68bba04c1dcb13e378486d"
metafile = true

[[files]]
file = "mods/decorative-blocks.pw.toml"
hash = "06118184bb0ec6bfd407aa120fa28fce9031ddedab3c710a315b161fa1d1a6b1"
metafile = true

[[files]]
file = "mods/drogtor.pw.toml"
hash = "6aac65adbbc8fba3a165b7207758ce133ff294dc1a0c111b66d22ca3362c310c"
metafile = true

[[files]]
file = "mods/ecologics.pw.toml"
hash = "1728e54a414ac18f912cfcb1669a3b180f78e47bbd52175d6d00d5682f82e1d0"
metafile = true

[[files]]
file = "mods/eldritch-mobs.pw.toml"
hash = "8870c2f8e0f5a7e2388a91691fecfd826e8d1cf7cd1eec484b006d0d8b516868"
metafile = true

[[files]]
file = "mods/emi-loot.pw.toml"
hash = "bafad65f31fdd578bc7c0cd5de6f547c83f364725c63db75336b6c246be05285"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "0395722100397e394dfddec723017c1ea18433f371250f80dae911b4e1c8b0d9"
metafile = true

[[files]]
file = "mods/emicompat.pw.toml"
hash = "da067d2511a56cb765093222bf2dac16c9e9a739d4157fa6876a0bb7dbd1b43e"
metafile = true

[[files]]
file = "mods/emitrades.pw.toml"
hash = "cfcfcb3c97190708fe47074148d803d339713bdaa908b98d57a6ef4e40e053b5"
metafile = true

[[files]]
file = "mods/emoji-type.pw.toml"
hash = "7a6a192d8b94f9363b7a741b6758316437c56598ee0156c479949e71b6c80f7c"
metafile = true

[[files]]
file = "mods/enchancement.pw.toml"
hash = "3500e041d1ab385c93b4926337aea11ce5de25ddd1896fa13d7164979015acef"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "a0fe34e6203463d22149437fcd4b0ace68d705850b4b4c57bc4a25fa62660eef"
metafile = true

[[files]]
file = "mods/expanded-storage.pw.toml"
hash = "d3e60634a4a07db0c9d17b8b4a6b492be9bea987fb63f94476e1204822eca2bb"
metafile = true

[[files]]
file = "mods/extraalchemy.pw.toml"
hash = "5031d54b22478641c4f70b444ce533e342c81d86e08df6c8072a032235a817f0"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "5153b742252cd104d2fd71eea311d7523ba1b808ef832f1b8a9b7ede7c12a6e2"
metafile = true

[[files]]
file = "mods/farmers-delight-fabric.pw.toml"
hash = "727869639af298412ec7c36601a46ea1607d455cd127283f74109491d3ce86ff"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "1d87f8c04eeed21a9544cfad7f64afee6de58b5249a70b0367ba8522273a4816"
metafile = true

[[files]]
file = "mods/fld.pw.toml"
hash = "55a95a2981ebeb0b5712d9feffb967269821633576817468191e3eef5d5bce5e"
metafile = true

[[files]]
file = "mods/forge-config-api-port-fabric.pw.toml"
hash = "bd0b18cb35442cf039162687e5b2999a1e8c77686678ea5a5fd9d964dad08140"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "1c736870931d9733fcb086e12e12cbce11fce835e41803dcd88fe41635f1f125"
metafile = true

[[files]]
file = "mods/half-doors.pw.toml"
hash = "fd34910c7292b2b48bb57c2b348c968cf5ea58f7c19683bf662ef801d167e233"
metafile = true

[[files]]
file = "mods/hookshot.pw.toml"
hash = "612a781cc620f3bbbcdf8fe6af0c2d52d57d80e85b2243f21ec027500e8c4107"
metafile = true

[[files]]
file = "mods/iceberg-fabric.pw.toml"
hash = "9a2f80adb3ee17c60a6ec5e0bb8800aa37345655fcba54cfd2f9da5e768b9887"
metafile = true

[[files]]
file = "mods/icy-incitement.pw.toml"
hash = "d4439c2d88668eb6065b34079d3a508988282588cca0faf392b04549e8a38b15"
metafile = true

[[files]]
file = "mods/immersive-paintings.pw.toml"
hash = "e7506764d7ba8d651a471e5d1dee9827b59c1ace77a3bab93e138d86644f8be9"
metafile = true

[[files]]
file = "mods/impaled.pw.toml"
hash = "232c69d47c4466a97e5e6717940d57407438a99cb91b665349fb4282d8f76243"
metafile = true

[[files]]
file = "mods/improved-signs.pw.toml"
hash = "cfdd24cdabb6d1c96528e35ffea48d4a4b88f471ca792e32e93155c64ca10314"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "e8168531c092676d47cac3657bfc525f096f11ff5372ce6e322ad57778b81635"
metafile = true

[[files]]
file = "mods/invview.pw.toml"
hash = "7cfacba402f52a71096bda72ede806b9b6964c2c807019da76f4e27fa839c8a5"
metafile = true

[[files]]
file = "mods/kofi-table.pw.toml"
hash = "8726c3ef33756d400f3f5fc00da96608ced3a11742682ef29bd4287225fe70d8"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "b4ca05b39b85c27cd97ccb65d5fb832f5e9fd7ee5710542a3e69dfa30a97ea7d"
metafile = true

[[files]]
file = "mods/legendary-tooltips-fabric.pw.toml"
hash = "70d7f9b16fffbf8999a373d3b008e6b0b7b782b9de14575826a0b2c86797636b"
metafile = true

[[files]]
file = "mods/light-overlay.pw.toml"
hash = "54037e4122f477f500dc3002b2f0ab9cda99d0fceb70da1d163be1afc99ec060"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "d2a65b42dcefbda9ac5c170ff5bf59b4a56ba192993a13d0b0da9b1f0678b4b3"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "27e73e63118d0afa759317328e8d54bc1512bb6ed69ad96b6dca9ed472aba43f"
metafile = true

[[files]]
file = "mods/macaws-trapdoors.pw.toml"
hash = "5dd16ad9b4057da6697197872580a42f92cbc3bf2a464871b8ff349163ea3f98"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
hash = "d3b441fc147721fe2c498ccd17809ce2b5dc6d9714d33d66ef4e69d61e907e88"
metafile = true

[[files]]
file = "mods/mcdiscordchat.pw.toml"
hash = "75899f5e221d068d54a3c531fa7c7b035cc05ca20e98b484cffaaf2df1032ebb"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "3a73a952e139f4f845dad83f2e206830ba5533cad7ab857e9843a038940d8b33"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "4ff1e58c9c7fdce5cd5a392987c3013d02ce63ee2ed4149098389a85caac2838"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "8f554f10f3ca26505c1f51871263a7d75fca1e07a288c60c1a96b18f830beede"
metafile = true

[[files]]
file = "mods/mouse-wheelie.pw.toml"
hash = "ab9f1a44770958246ddee1e25a0748ca8c4597daceadebe7ecd3b59b50df7951"
metafile = true

[[files]]
file = "mods/naturalist.pw.toml"
hash = "928049dc37b7b41a8d7cadf9977d183527c74744f9dce884c9c04a76b3276832"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "525ad62238789b624a578c329bf6f8e04160055b107527b3f75471c41dd164a9"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "1aa7510ec1a3994273a20f8b341f676583b9ede2eaea3badd46deb7178d92a6c"
metafile = true

[[files]]
file = "mods/paintings.pw.toml"
hash = "28af23724a7b1a82b41b983445f891a0752652f2034b5bf0fa7b344210eb2a6b"
metafile = true

[[files]]
file = "mods/patchouli-fabric.pw.toml"
hash = "0103115337ebe895bb4802a4de51d9ea8f130112581b9cdf28ed3abee59d50de"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "2dab4b3cea2f1ce1505c3c7be55d8fb6123a7593435134f2c15eed18e6c07ddf"
metafile = true

[[files]]
file = "mods/peculiar-pieces.pw.toml"
hash = "6dc36572ee7f1dbc169b9ac9bb1210c03541a5e27b028a490a16775d76fedcb2"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
hash = "527279ca4b9a30e756139465d01009482bafc3e2992c96947118a56e0bce293f"
metafile = true

[[files]]
file = "mods/pick-your-poison.pw.toml"
hash = "7d521085ff1a7c50a66ff9b8a1e14639440746fb08c829b83bdc1fac0986ef22"
metafile = true

[[files]]
file = "mods/piercing-paxels.pw.toml"
hash = "215c6991f2f4c7e81ecb0c67bab828fe928bcf329f60e0729608efebaed23854"
metafile = true

[[files]]
file = "mods/prism-fabric.pw.toml"
hash = "ad2cabc8f0042248e26eb19c78f68ab9adde8a2a8e35979f84950b98a32c34f3"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "1c6d01b013b9e8c6dd921046adc7c7768814c17a0fde45cbe695c8e2de40f8be"
metafile = true

[[files]]
file = "mods/renameit.pw.toml"
hash = "77bd6ae651e3f55796c48e203745c266cbc46c192b1043f4a9d24b8071bdc1bf"
metafile = true

[[files]]
file = "mods/repurposed-structures-fabric.pw.toml"
hash = "8e38ff256bfb7a0dc1c1399b723ceb2dcdac62f877975bdf5483c7b9271cf344"
metafile = true

[[files]]
file = "mods/selene.pw.toml"
hash = "1ae8431c49e933f79fd261fdc59823b3b6194dcaee4c06333fd2a72d43d8838e"
metafile = true

[[files]]
file = "mods/simple-copper-pipes.pw.toml"
hash = "fa5a180691832246b5fa21d994c2e1456066dfefb594e70845f49a3811fd09d7"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "88471e004fced6d0f52a1fde7ac04c3ebc653f5775aa586437ad3d9a64080e8d"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "99c83e926faf4565a4a75f8666a9c68721c3effdeece027509e23c5d50395321"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "aa4dcf55ac3191b0b31437521714c1d28364c3396cf06ef07fa76a08488c1837"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "2aeab4f3b0a720ed02f400d9b521f1858474d4f8f7c3577ce916d5aa31fe37e1"
metafile = true

[[files]]
file = "mods/styledplayerlist.pw.toml"
hash = "d2accfdeb772987301d7517f93e081a276e5ae7610caf1f213a2012204699358"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "b7d2a5c2574157379982bc80aa3f04c19e7be1b681eb1b8233b85058e728e14c"
metafile = true

[[files]]
file = "mods/terrablender-fabric.pw.toml"
hash = "da5ef6d6ea7ab0a7b0691bb54091dddeb4bf462258756aec1f479ab9f6e62466"
metafile = true

[[files]]
file = "mods/the-bumblezone-fabric.pw.toml"
hash = "3cfac0afbfd2d5f5a6d6a9cf00f6ccda4e4afed71d6831102a562caafad8dd6b"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "2d87e18db16ceb34da29277e49f0df0de1e7b1f52d0efc8b4d93749d2f32415c"
metafile = true

[[files]]
file = "mods/transparent.pw.toml"
hash = "fc21f4ec695874f7e05b52a9115f9b2616b5a6a84cb58f6567b3e1f308e427ed"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "842711b0a1baa2fc6bd2ef6c1953c735f68e73c6b7a13dee723851feb183349c"
metafile = true

[[files]]
file = "mods/visible-barriers.pw.toml"
hash = "8d77350dc3410226e42685008053d939f175b84769a880ec4db91cf6485fbda7"
metafile = true

[[files]]
file = "mods/wanderers-catalogue.pw.toml"
hash = "03c7682c6da0b60c7aa3f91b988562b118052f5bdaebb2403cc26b8ee72e99c2"
metafile = true

[[files]]
file = "mods/webstreamer.pw.toml"
hash = "4f2bdd95b949181028ba388d4c72b2b971f9b950b0a6034ee4d4f954126069de"
metafile = true

[[files]]
file = "mods/whipdashing.pw.toml"
hash = "3586839f1b62284d5b0ea044bd1af0555c6a8820e5dd829cb4cbb3a4e55df0f8"
metafile = true

[[files]]
file = "mods/yttr-6.599+1.19.jar"
hash = "a3525975618c1e9b9beaf5878e3bba55b28026050b1504654a9e3723179725ed"

[[files]]
file = "mods/yungs-api-fabric.pw.toml"
hash = "cd37432982096708513ea99f46734d3407f26e1b69df399722de5fd4e089e10a"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples-fabric.pw.toml"
hash = "1469f6544880a7c8962d4e277f3c00f54ec08a3bdb20ddeb9e11a8a36d839021"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons-fabric.pw.toml"
hash = "6b98f78113cddfd12400b0e981de0a3c427ca9db42a11d6d438ed728133a790c"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts-fabric.pw.toml"
hash = "17d172d8eba1234a2eeb7569b080ff17424f2aeee6b2949f9498230f1c71bca9"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments-fabric.pw.toml"
hash = "feb38d4a8ed796be0dd60f50bd0f56a83a6df5f6fb57d13bad5bd0481017ec12"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds-fabric.pw.toml"
hash = "f226c76915922eff0167fac761a4961576cb4ea0159871c4796813c93511073a"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts-fabric.pw.toml"
hash = "e217989faf390b38782c83f9ef1002a95a69c37754d975833b69fcc843b7eeef"
metafile = true

[[files]]
file = "mods/yungs-bridges-fabric.pw.toml"
hash = "a4ed395ffbaa758f6b20cb9f2513189bc803c6998091bff839d9dbdeb8c4ad75"
metafile = true

[[files]]
file = "mods/yungs-extras-fabric.pw.toml"
hash = "b2b5c11320601e1bccb196404515ad8f6b35ccb6db508db785806d483b71085b"
metafile = true

[[files]]
file = "options.txt"
hash = "647b9816fd13c315f11f8303dd13a5c4ddb7cde0b635bf6bf00a62140f610ce2"
